name: Swift Foundation Android CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - '*'
  schedule:
    - cron:  '30 6,17 * * *'
jobs:
  test:
    # Runner must be macos-13, since lack of nested virtualization support on macos-14 prevents the Android emulator from working
    # see: https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#limitations-for-arm64-macos-runners
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - name: "Test Swift (6.0) Package on Android"
        uses: skiptools/swift-android-action@v1
        with:
          swift-version: 6.0
      - name: "Cleanup build"
        run: rm -rf .build
      - name: "Test Swift (5.10.1) Package on Android"
        uses: skiptools/swift-android-action@v1
        with:
          swift-version: 5.10.1

